use_frameworks!
target 'Web3_Tests' do
  pod 'MagicSDK-Web3', :path => '../'
  pod 'MagicSDK-Web3/PromiseKit', :path => '../'
  pod 'MagicSDK-Web3/ContractABI', :path => '../'

  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.2'
end
